### PR TITLE
Archi 5.1.0 and co archi 0.8.8 and improvements and bugfix

### PR DESCRIPTION
**Pull request by benjamin-feron**
- Update Archi from version 4.9.3 to 5.1.0
- Update coArchi plugin from version 0.8.2.202202161341 to 0.8.8.202306191101
- wget is no longer necessary since the download is done with curl.
- jq is required for oAuth token authentication to work.
- dbus-x11 is optionally required to avoid these warnings on create html report :
  SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)
  SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)
- The Archi download command (curl) makes a GET request and no longer a POST.
  The URL for Archi 5 ends with "archi5.php"
  The SSL certificate is verified for added security.
  Parameters passed in URL are more readable.
- The Archi home directory for Archi v5 is no longer ~/.archi4 but ~/.archi
- There is a typo with -saveModel on create html report command (-saveModel -> --saveModel) but in any case, this argument is not necessary so it can be removed.

### CODE REVIEW

**Comment by aurelien23** [comment]
Hello,
Thank you for this pull request !
I just change the name of the coArchi plugins. And restore the -saveModel in create-htmlreport.periodically.sh, because we need it for our internal use..

**Comment by benjamin-feron** [comment]
Your welcome !
But didn't you forget a "-" (--saveModel) ?

**Comment by aurelien23** [comment]
No it's ok like that with just one - . 
We use the XML model to generate HTML dictonaries, for internal use.

**Comment by benjamin-feron** [comment]
All right

**Pull request merged**
