### PR TITLE
Update Archi version

### PR DESCRIPTION
**Pull request by inngvar**

### CODE REVIEW

**Comment by kerphi** [comment]
Hello @inngvar, thank you for your contribution! it's a good surprise for us (we are located at Montpellier and working for [Abes](https://abes.fr/en/))
Could I ask you where are you from and tell us a bit about your use case?

**Comment by inngvar** [comment]
Hello @kerphi I am from Russia. Our team is working on implementing reference model made in archi(https://bian.org/), and we had problems on generating html reports. While trying to solve a problem problem version of archi was updated.

**Comment by kerphi** [comment]
Great, and which kind of problems did you solved thanks to the new versions? (ENV ARCHI_VERSION 4.7.1 / ENV ARCHI_PLUGIN_MODELREPOSITORY_VERSION 0.6.2.202004031233 )

**Comment by inngvar** [comment]
@kerphi 
We have two problems:
* Some of images in reports was just painted black, Unfortunately the problem was not solved.
* Report did not finish correctly. This was fixed by setting   _JAVA_OPTIONS=-Xmx4024m and archi version update

**Comment by kerphi** [comment]
Ok, the JAVA_OPTIONS=-Xmx4024m is missing in your PR is it intentional? or maybe it could be fixed/configured in another way?

**Comment by inngvar** [comment]
> Ok, the JAVA_OPTIONS=-Xmx4024m is missing in your PR is it intentional? or maybe it could be fixed/configured in another way?

I think this option should be configured manually,  it will depends on model size.  We just have extremely large model.

**Comment by kerphi** [comment]
We could add a docker parameter for this if it could help?
Do you know where and how this option should be setup?
I guess near this code: https://github.com/abes-esr/archi-htmlreport-docker/blob/master/create-htmlreport.periodically.sh#L34-L39

**Comment by inngvar** [comment]
> We could add a docker parameter for this if it could help?
> Do you know where and how this option should be setup?
> I guess near this code: https://github.com/abes-esr/archi-htmlreport-docker/blob/master/create-htmlreport.periodically.sh#L34-L39

I configure it in docker-compose.yml
`environment:
      - JAVA_OPTIONS=-Xmx4024m -Xms512m`
So  I don't think this setting should include in docker file

**Comment by kerphi** [comment]
Ok, i just added a JAVA_OPTIONS example embedded in the docker-compose.yml example:
https://github.com/abes-esr/archi-htmlreport-docker/commit/3352a485fac02026a6bc076a2f0af0bf561c4373

It could be useful for peoples

**Comment by kerphi** [comment]
We are going to merge your PR and we will try to update the Archi version because it seams that 4.7.1 version is not available anymore.
The wget to get the latest version is maybe something like that:
```
wget --output-document="Archi-Linux64-4.8.1.tgz" --post-data="dl=Archi-Linux64-4.8.1.tgz" https://www.archimatetool.co
m/downloads/archi/
```

**Comment by kerphi** [comment]
@inngvar this is ok, we just updated the Archi version and the correct plugin and a new docker image is available: 1.4.0
https://hub.docker.com/r/abesesr/archi-htmlreport-docker

**Pull request merged**
